// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking/identity/v1/user_login_attempt.proto

package com.tracking.identity.v1;

public interface UserLoginAttemptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracking.identity.v1.UserLoginAttempt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>.tracking.identity.v1.UserLoginAttempt.Result result = 3;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.tracking.identity.v1.UserLoginAttempt.Result result = 3;</code>
   * @return The result.
   */
  com.tracking.identity.v1.UserLoginAttempt.Result getResult();
}
