// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking/identity/v1/user_login_attempt.proto

package com.tracking.identity.v1;

public final class UserLoginAttemptProto {
  private UserLoginAttemptProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_identity_v1_UserLoginAttempt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_identity_v1_UserLoginAttempt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-tracking/identity/v1/user_login_attemp" +
      "t.proto\022\024tracking.identity.v1\032%protobuf/" +
      "extension/v1/extension.proto\"\330\001\n\020UserLog" +
      "inAttempt\022\017\n\007user_id\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022=" +
      "\n\006result\030\003 \001(\0162-.tracking.identity.v1.Us" +
      "erLoginAttempt.Result\"C\n\006Result\022\022\n\016RESUL" +
      "T_INVALID\020\000\022\022\n\016RESULT_SUCCESS\020\001\022\021\n\rRESUL" +
      "T_FAILED\020\002:#\202\265\030\037tracking.identity.login-" +
      "attemptBT\n\030com.tracking.identity.v1B\025Use" +
      "rLoginAttemptProtoP\001Z\037tracking/identity/" +
      "v1;identityv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protobuf.extension.v1.ExtensionProto.getDescriptor(),
        });
    internal_static_tracking_identity_v1_UserLoginAttempt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tracking_identity_v1_UserLoginAttempt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_identity_v1_UserLoginAttempt_descriptor,
        new java.lang.String[] { "UserId", "Ip", "Result", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.protobuf.extension.v1.ExtensionProto.topicName);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.protobuf.extension.v1.ExtensionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
