// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/extension/v1/extension.proto

package com.protobuf.extension.v1;

public final class ExtensionProto {
  private ExtensionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.protobuf.extension.v1.ExtensionProto.topicName);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int TOPIC_NAME_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> topicName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%protobuf/extension/v1/extension.proto\022" +
      "\025protobuf.extension.v1\032 google/protobuf/" +
      "descriptor.proto:5\n\ntopic_name\022\037.google." +
      "protobuf.MessageOptions\030\320\206\003 \001(\tBQ\n\031com.p" +
      "rotobuf.extension.v1B\016ExtensionProtoP\001Z\"" +
      "protobuf/extension/v1/;extensionv1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    topicName.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
